### ISSUE TITLE
As an admin I want to be able to track user activities on our website so that I can improve the UI/UX and identify product and site usage trends.

### ISSUE THREAD

**Issue by KimmoKAhola** [KYH-Net23/LoggingService#1]
Authors: Kimmo Ahola & Isabel Haataja

# Acceptance Criteria:
- [x] User interactions should be logged and stored.
- [ ] The user information should be anonymous.
- [ ] Information about Demographics, gender should be saved.
- [ ] Login duration should be saved.
- [ ] Wishlist history should be saved.

# Tasks:
- [x] KYH-Net23/LoggingService#4
- [ ] KYH-Net23/LoggingService#3
- [ ] KYH-Net23/LoggingService#2
- [ ] KYH-Net23/LoggingService#5
- [x] KYH-Net23/Rika#95
- [x] KYH-Net23/LoggingService#7
- [x] KYH-Net23/LoggingService#8

# Test Cases:
### Steps:
- [ ] Log in as a customer with valid user credentials.
- [ ] Compare the user's login history.
### Expected Results: 
- [ ] The user's login history gets updated and saved to the database. 
- [ ] The number of times visited should be increased by one.

### Steps:
- [ ] Log in as a customer with valid user credentials.
- [ ] Wait a minute.
- [ ] Log out.
- [ ] Compare the user's login history timestamp.
### Expected Results: 
- [ ] The user's login history should contain the correct duration.

### Prerequisites: 
- [ ] The file for tracking interactions gets loaded on the product page.
- [ ] Saving products to the wishlist has been implemented.
### Steps:
- [ ] Log in as a customer with valid user credentials.
- [ ] Navigate to the product page.
- [ ] Choose a product and add it to the wishlist.
### Expected Results: 
- [ ] The product added to the wishlist gets saved to the database along with its information. 

### Prerequisites: 
- [ ] The file for tracking interactions gets loaded on the product page.
### Steps:
- [ ] Log in as a customer with valid user credentials.
- [ ] Navigate to the product page.
- [ ] Click on a product.
### Expected Results: 
- [ ] The product page and the chosen product’s information gets saved to the database.

# Activity Diagram:

![Image](https://github.com/user-attachments/assets/2624a6f1-fe1c-4d90-b436-6d626ccaeccd)
