### ISSUE TITLE
As an admin, I want to be able to search and filter the change history overview, so that I can quickly find specific actions taken by other admins based on criteria such as action type, or admin user.

### ISSUE THREAD

**Issue by IsabelHaataja** [KYH-Net23/LoggingService#9]
Authors: Kimmo Ahola & Isabel Haataja

## Acceptance Criteria:
- [ ] The admin can input a search string to find specific activities.
- [ ] The admin can filter users depending on user type (admin, customer).
- [ ] The admin can sort search results based on different fields.
- [ ] The search result should display Name, User type, User ID, Active/Inactive and a show details button.
- [ ] The admin can clear selected filters.
- [ ] The admin can apply pagination rules (results per page).
- [ ] The search results should update after every keystroke.
- [ ] If there are no results a special message should be displayed.

## Tasks:
- [ ] KYH-Net23/Rika#124
- [ ] KYH-Net23/Rika#123
- [ ] Implement a “Apply Filter” button.
- [ ] Implement a “Clear filters” button.
- [ ] KYH-Net23/Rika#125
- [ ] KYH-Net23/Rika#126
- [ ] KYH-Net23/Rika#127

## Activity Diagram:
![Image](https://github.com/user-attachments/assets/97dc253f-dba8-4dba-b78d-bc389f11d616)

## Test Cases:
- [ ] **Case 1:**
Prerequisites: The user is logged in as an admin
Steps:
1. Leave the fields empty.
2. Press “Apply filter”.
Expected Results: The page stays as it is.

- [ ] **Case 2:**
Prerequisites: The user is logged in as an admin.
Steps:
1. The user applies a change type filter with “change_type” selected.
2. The user presses “Apply filter button”
Expected Results: Only the users with the selected change type are visible.

- [ ] **Case 3:**
Prerequisites: The user is logged in as an admin.
Steps:
The user searches for a user id/username that does not exist.
The user presses “search”.
Expected Results: A message is displayed saying that the user could not be found.

- [ ] **Case 4:**
Prerequisites: The user is logged in as an admin.
Steps:
The user searches for an admin id/username that does not exist.
The user presses “search”.
Expected Results: A message is displayed saying that the user could not be found.
